INSERT INTO roles(user_role) VALUES ('FIREFIGHTER') ON CONFLICT DO NOTHING;
INSERT INTO roles(user_role) VALUES ('PUBLIC') ON CONFLICT DO NOTHING;
INSERT INTO roles(user_role) VALUES ('SUPERADMIN') ON CONFLICT DO NOTHING;